[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_staking = "CgmvUGyVzKhKmMEDM5Hwd3T9ucUXAKTePZYYscYcpjsQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[build]
bpf_sdk = "/Users/parth/solana/sdk/bpf"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
